apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/devfile-sample/devfile-sample@sha256:4f1c3325bd43ec0f5b1475ed7a086ced49b6429be4263203d3a8ad1575dff385
        name: my-nodejs
        resources: {}
status: {}
